-- CREATE TABLE IF NOT EXISTS `Users` (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     pseudo VARCHAR(25) NOT NULL UNIQUE,
--     email  VARCHAR(45) NOT NULL UNIQUE,
--     password TEXT NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS Users (username TEXT, email TEXT, password TEXT )

DELETE FROM Users;